
export const SET_DIENTHOAI_API = 'SET_DIENTHOAI_API';

export const GET_DIENTHOAI_API = 'GET_DIENTHOAI_API';
export const ADD_DIENTHOAI_API = 'ADD_DIENTHOAI_API';
export const DELETE_DIENTHOAI_API = 'DELETE_DIENTHOAI_API';
export const PUT_DIENTHOAI_API = 'PUT_DIENTHOAI_API';